#ifndef _INTERH
#define _INTERH

#define DEA POSITION_DEAD
#define MOR POSITION_MORTALLYW
#define INC POSITION_INCAP
#define STU POSITION_STUNNED
#define SLE POSITION_SLEEPING
#define RES POSITION_RESTING
#define PRY POSITION_PRAYING
#define FIG POSITION_FIGHTING
#define STA POSITION_STANDING
#define SIT POSITION_SITTING

#define NONE 0

struct command_info cmd_info[] = {
  { "north",         STA, 0,           do_move,          0, NONE           },
  { "east",          STA, 0,           do_move,          0, NONE           },
  { "south",         STA, 0,           do_move,          0, NONE           },
  { "west",          STA, 0,           do_move,          0, NONE           },
  { "up",            STA, 0,           do_move,          0, NONE           },
  { "down",          STA, 0,           do_move,          0, NONE           },
  { "enter",         STA, 0,           do_enter,         0, NONE           },
  { "exits",         RES, 0,           do_exits,         0, NONE           },
  { "kiss",          RES, 0,           do_action,        0, NONE           },
  { "get",           RES, 0,           do_get,           0, NONE           },
  { "drink",         RES, 0,           do_drink,         0, NONE           }, /* 11 */
  { "eat",           RES, 0,           do_eat,           0, NONE           },
  { "wear",          RES, 0,           do_wear,          0, NONE           },
  { "wield",         RES, 0,           do_wield,         0, NONE           },
  { "look",          RES, 0,           do_look,          0, NONE           },
  { "score",         DEA, 0,           do_score,         0, NONE           },
  { "say",           RES, 0,           do_say,           0, NONE           },
  { "shout",         RES, 6,           do_shout,         0, NONE           },
  { "tell",          RES, 0,           do_tell,          0, NONE           },
  { "inventory",     DEA, 0,           do_inventory,     0, NONE           },
  { "qui",           DEA, 0,           do_qui,           0, NONE           }, /* 21 */
  { "bounce",        STA, 0,           do_action,        0, NONE           },
  { "smile",         RES, 0,           do_action,        0, NONE           },
  { "dance",         STA, 0,           do_action,        0, NONE           },
  { "kill",          FIG, 0,           do_kill,          0, NONE           },
  { "cackle",        RES, 0,           do_action,        0, NONE           },
  { "laugh",         RES, 0,           do_action,        0, NONE           },
  { "giggle",        RES, 0,           do_action,        0, NONE           },
  { "shake",         RES, 0,           do_action,        0, NONE           },
  { "puke",          RES, 0,           do_puke,          0, NONE           },
  { "growl",         RES, 0,           do_action,        0, NONE           }, /* 31 */
  { "scream",        RES, 0,           do_action,        0, NONE           },
  { "insult",        RES, 0,           do_action,        0, NONE           },
  { "comfort",       RES, 0,           do_action,        0, NONE           },
  { "nod",           RES, 0,           do_action,        0, NONE           },
  { "sigh",          RES, 0,           do_action,        0, NONE           },
  { "sulk",          RES, 0,           do_action,        0, NONE           },
  { "help",          DEA, 0,           do_help,          0, NONE           },
  { "who",           DEA, 0,           do_who,           0, NONE           },
  { "emote",         SLE, 2,           do_emote,         0, NONE           },
  { "echo",          SLE, 1,           do_echo,          0, NONE           }, /* 41 */
  { "stand",         RES, 0,           do_stand,         0, NONE           },
  { "sit",           RES, 0,           do_sit,           0, NONE           },
  { "rest",          RES, 0,           do_rest,          0, NONE           },
  { "sleep",         SLE, 0,           do_sleep,         0, NONE           },
  { "wake",          SLE, 0,           do_wake,          0, NONE           },
  { "force",         DEA, GOD,         do_force,         0, NONE           },
  { "transfer",      DEA, SAINT,       do_trans,         0, NONE           },
  { "hug",           RES, 0,           do_action,        0, NONE           },
  { "snuggle",       RES, 0,           do_action,        0, NONE           },
  { "cuddle",        RES, 0,           do_action,        0, NONE           }, /*51*/
  { "nuzzle",        RES, 0,           do_action,        0, NONE           },
  { "cry",           RES, 0,           do_action,        0, NONE           },
  { "news",          DEA, 0,           do_news,          0, NONE           },
  { "equipment",     SLE, 0,           do_equipment,     0, NONE           },
  { "buy",           STA, 0,           do_not_here,      0, NONE           },
  { "sell",          STA, 0,           do_not_here,      0, NONE           },
  { "value",         RES, 0,           do_not_here,      0, NONE           },
  { "list",          RES, 0,           do_not_here,      0, NONE           },
  { "drop",          RES, 0,           do_drop,          0, NONE           },
  { "goto",          DEA, IMMORTAL,    do_goto,          0, NONE           }, /* 61 */
  { "weather",       RES, 0,           do_weather,       0, NONE           },
  { "read",          RES, 0,           do_read,          0, NONE           },
  { "pour",          RES, 0,           do_pour,          0, NONE           },
  { "grab",          RES, 0,           do_grab,          0, NONE           },
  { "remove",        RES, 0,           do_remove,        0, NONE           },
  { "put",           RES, 0,           do_put,           0, NONE           },
  { "shutdow",       DEA, SILLYLORD,   do_shutdow,       0, NONE           },
  { "save",          SLE, 0,           do_save,         25, NONE           },
  { "hit",           FIG, 0,           do_hit,           0, NONE           },
  { "string",        DEA, SAINT,       do_string,        0, NONE           }, /* 71 */
  { "give",          RES, 0,           do_give,          0, NONE           },
  { "quit",          DEA, 0,           do_quit,          0, NONE           },
  { "stat",          DEA, CREATOR,     do_stat,          0, NONE           },
  { "guard",         STA, 1,           do_guard,         0, NONE           },
  { "time",          DEA, 0,           do_time,          0, NONE           },
  { "load",          DEA, DEMIGOD,     do_load,          0, NONE           },
  { "purge",         DEA, LESSER_GOD,  do_purge,         0, NONE           },
  { "shutdown",      DEA, SILLYLORD,   do_shutdown,      0, NONE           },
  { "idea",          DEA, 2,           do_idea,          0, NONE           },
  { "typo",          DEA, 2,           do_typo,          0, NONE           }, /* 81 */
  { "bug",           DEA, 2,           do_bug,           0, NONE           },
  { "whisper",       RES, 2,           do_whisper,       0, NONE           },
  { "cast",          RES, 1,           do_cast,          0, NONE           },
  { "at",            DEA, REAL_IMMORT, do_at,            0, NONE           },
  { "ask",           RES, 0,           do_ask,           0, NONE           },
  { "order",         RES, 2,           do_order,         0, NONE           },
  { "sip",           RES, 0,           do_sip,           0, NONE           },
  { "taste",         RES, 0,           do_taste,         0, NONE           },
  { "snoop",         DEA, LESSER_GOD,  do_snoop,         0, NONE           },
  { "follow",        RES, 0,           do_follow,        0, NONE           }, /* 91 */
  { "rent",          STA, 1,           do_not_here,      0, NONE           },
  { "offer",         STA, 1,           do_not_here,      0, NONE           },
  { "poke",          RES, 0,           do_action,        0, NONE           },
  { "advance",       DEA, IMPLEMENTOR, do_advance,       0, NONE           },
  { "accuse",        RES, 0,           do_action,        0, NONE           },
  { "grin",          RES, 0,           do_action,        0, NONE           },
  { "bow",           STA, 0,           do_action,        0, NONE           },
  { "open",          RES, 0,           do_open,          0, NONE           },
  { "close",         RES, 0,           do_close,         0, NONE           },
  { "lock",          RES, 0,           do_lock,          0, NONE           }, /* 101 */
  { "unlock",        RES, 0,           do_unlock,        0, NONE           }, 
  { "leave",         STA, 0,           do_leave,         0, NONE           },
  { "applaud",       RES, 0,           do_action,        0, NONE           },
  { "blush",         RES, 0,           do_action,        0, NONE           },
  { "burp",          RES, 0,           do_action,        0, NONE           },
  { "chuckle",       RES, 0,           do_action,        0, NONE           },
  { "clap",          RES, 0,           do_action,        0, NONE           },
  { "cough",         RES, 0,           do_action,        0, NONE           },
  { "curtsey",       STA, 0,           do_action,        0, NONE           },
  { "fart",          RES, 0,           do_action,        0, NONE           }, /*111*/
  { "flip",          STA, 0,           do_action,        0, NONE           },
  { "fondle",        RES, 0,           do_action,        0, NONE           },
  { "frown",         RES, 0,           do_action,        0, NONE           },
  { "gasp",          RES, 0,           do_action,        0, NONE           },
  { "glare",         RES, 0,           do_action,        0, NONE           },
  { "groan",         RES, 0,           do_action,        0, NONE           },
  { "grope",         RES, 0,           do_action,        0, NONE           },
  { "hiccup",        RES, 0,           do_action,        0, NONE           },
  { "lick",          RES, 0,           do_action,        0, NONE           },
  { "love",          RES, 0,           do_action,        0, NONE           }, /* 121 */
  { "moan",          RES, 0,           do_action,        0, NONE           },
  { "nibble",        RES, 0,           do_action,        0, NONE           },
  { "pout",          RES, 0,           do_action,        0, NONE           },
  { "purr",          RES, 0,           do_action,        0, NONE           },
  { "ruffle",        STA, 0,           do_action,        0, NONE           },
  { "shiver",        RES, 0,           do_action,        0, NONE           },
  { "shrug",         RES, 0,           do_action,        0, NONE           },
  { "sing",          RES, 0,           do_sing,          0, NONE           },
  { "slap",          RES, 0,           do_action,        0, NONE           },
  { "smirk",         RES, 0,           do_action,        0, NONE           }, /* 131 */
  { "snap",          RES, 0,           do_action,        0, NONE           },
  { "sneeze",        RES, 0,           do_action,        0, NONE           },
  { "snicker",       RES, 0,           do_action,        0, NONE           },
  { "sniff",         RES, 0,           do_action,        0, NONE           },
  { "snore",         SLE, 0,           do_action,        0, NONE           },
  { "spit",          STA, 0,           do_action,        0, NONE           },
  { "squeeze",       RES, 0,           do_action,        0, NONE           },
  { "stare",         RES, 0,           do_action,        0, NONE           },
  { "strut",         STA, 0,           do_action,        0, NONE           },
  { "thank",         RES, 0,           do_action,        0, NONE           },
  { "twiddle",       RES, 0,           do_action,        0, NONE           },
  { "wave",          RES, 0,           do_action,        0, NONE           },
  { "whistle",       RES, 0,           do_action,        0, NONE           },
  { "wiggle",        STA, 0,           do_action,        0, NONE           },
  { "wink",          RES, 0,           do_action,        0, NONE           },
  { "yawn",          RES, 0,           do_action,        0, NONE           },
  { "snowball",      STA, IMMORTAL,    do_action,        0, NONE           },
  { "write",         RES, 0,           do_write,         0, NONE           },
  { "hold",          RES, 0,           do_grab,          0, NONE           },
  { "flee",          SIT, 1,           do_flee,        100, CMDF_FLUSH     }, /* 151 */
  { "sneak",         STA, 1,           do_sneak,         0, NONE           },
  { "hide",          RES, 1,           do_hide,          0, NONE           },
  { "backstab",      STA, 1,           do_backstab,      0, NONE           },
  { "pick",          STA, 1,           do_pick,          0, NONE           },
  { "steal",         STA, 1,           do_steal,         0, NONE           },
  { "bash",          FIG, 1,           do_bash,          0, NONE           },
  { "rescue",        FIG, 1,           do_rescue,       50, CMDF_FLUSH     },
  { "kick",          FIG, 1,           do_kick,          0, NONE           },
  { "french",        RES, 0,           do_action,        0, NONE           },
  { "comb",          RES, 0,           do_action,        0, NONE           }, /* 161 */
  { "massage",       RES, 0,           do_action,        0, NONE           },
  { "tickle",        RES, 0,           do_action,        0, NONE           },
  { "practice",      RES, 1,           do_practice,      0, NONE           },
  { "pat",           RES, 0,           do_action,        0, NONE           },
  { "examine",       RES, 0,           do_examine,       0, NONE           },
  { "take",          RES, 0,           do_get,           0, NONE           },
  { "info",          DEA, 0,           do_info,          0, NONE           },
  { "'",             RES, 0,           do_say,           0, NONE           },
  { "practise",      RES, 0,           do_practice,      0, NONE           },
  { "curse",         RES, 0,           do_action,        0, NONE           }, /* 171 */
  { "use",           RES, 0,           do_use,           0, NONE           },
  { "where",         DEA, DEMIGOD,     do_where,         0, NONE           },
  { "levels",        DEA, 0,           do_levels,        0, NONE           },
  { "reroll",        DEA, IMPLEMENTOR, do_reroll,        0, NONE           },
  { "pray",          RES, 0,           do_pray,          0, NONE           },
  { ",",             SLE, 2,           do_emote,         0, NONE           },
  { "beg",           RES, 0,           do_action,        0, NONE           },
  { "bleed",         RES, 0,           do_not_here,      0, NONE           },
  { "cringe",        RES, 0,           do_action,        0, NONE           },
  { "daydream",      SLE, 0,           do_action,        0, NONE           }, /* 181 */
  { "fume",          RES, 0,           do_action,        0, NONE           },
  { "grovel",        RES, 0,           do_action,        0, NONE           },
  { "hop",           RES, 0,           do_action,        0, NONE           },
  { "nudge",         RES, 0,           do_action,        0, NONE           },
  { "peer",          RES, 0,           do_action,        0, NONE           },
  { "point",         RES, 0,           do_action,        0, NONE           },
  { "ponder",        RES, 0,           do_action,        0, NONE           },
  { "punch",         RES, 0,           do_action,        0, NONE           },
  { "snarl",         RES, 0,           do_action,        0, NONE           },
  { "spank",         RES, 0,           do_action,        0, NONE           }, /* 191 */
  { "steam",         RES, 0,           do_action,        0, NONE           },
  { "tackle",        RES, 0,           do_action,        0, NONE           },
  { "taunt",         RES, 0,           do_action,        0, NONE           },
  { "think",         RES, 0,           do_action,        0, NONE           },
  { "whine",         RES, 0,           do_action,        0, NONE           },
  { "worship",       RES, 0,           do_action,        0, NONE           },
  { "yodel",         RES, 0,           do_action,        0, NONE           },
  { "brief",         DEA, 0,           do_brief,         0, NONE           },
  { "wiznet",        DEA, IMMORTAL,    do_commune,       0, NONE           },
  { "consider",      RES, 0,           do_consider,      0, NONE           }, /* 201 */
  { "group",         RES, 0,           do_group,         0, NONE           },
  { "restore",       DEA, GOD,         do_restore,       0, NONE           }, /* 203 */
  { "return",        DEA, 0,           do_return,        0, NONE           },
  { "switch",        DEA, DEMIGOD,     do_switch,        0, NONE           }, /* 205 */
  { "quaff",         RES, 0,           do_quaff,         0, NONE           },
  { "recite",        RES, 0,           do_recite,        0, NONE           },
  { "users",         DEA, 0,           do_users,         0, NONE           },
  { "pose",          STA, 0,           do_pose,          0, NONE           },
  { "noshout",       DEA, REAL_IMMORT, do_noshout,       0, NONE           },
  { "wizhelp",       DEA, IMMORTAL,    do_wizhelp,       0, NONE           }, /* 211 */
  { "credits",       DEA, 0,           do_credits,       0, NONE           },
  { "compact",       DEA, 0,           do_compact,       0, NONE           },
  { ":",             SLE, 2,           do_emote,         0, NONE           },
  { "deafen",        RES, 0,           do_plr_noshout,   0, NONE           }, /* 215  */
  { "slay",          DEA, SILLYLORD,   do_kill,          0, NONE           }, /* 216 */
  { "wimp",          DEA, 0,           do_wimp,          0, NONE           },
  { "junk",          RES, 0,           do_junk,          0, NONE           },
  { "deposit",       RES, 0,           do_not_here,      0, NONE           },
  { "withdraw",      RES, 0,           do_not_here,      0, NONE           },
  { "balance",       RES, 0,           do_not_here,      0, NONE           }, /* 221 */
  { "nohassle",      DEA, IMMORTAL,    do_nohassle,      0, NONE           },
  { "system",        DEA, SILLYLORD,   do_system,        0, NONE           },
  { "pull",          STA, 0,           do_not_here,      0, NONE           },
  { "stealth",       DEA, GOD,         do_stealth,       0, NONE           },
  { "edit",          DEA, REAL_IMMORT, do_edit,          0, NONE           },
  { "form",          DEA, REAL_IMMORT, do_form,          0, NONE           },
  { "rsave",         DEA, REAL_IMMORT, do_rsave,         0, NONE           },
  { "rload",         DEA, REAL_IMMORT, do_rload,         0, NONE           },
  { "track",         STA, 1,           do_track,         0, NONE           },
  { "wizlock",       DEA, GOD,         do_wizlock,       0, NONE           }, /* 231 */
  { "highfive",      STA, 1,           do_highfive,      0, NONE           },
  { "title",         SLE, 1,           do_title,         0, NONE           },
  { "whozone",       DEA, 0,           do_who,           0, NONE           },
  { "assist",        STA, 0,           do_assist,        0, NONE           },
  { "attribute",     DEA, 0,           do_attribute,     0, NONE           },
  { "world",         DEA, 0,           do_world,         0, NONE           },
  { "spells",        DEA, 0,           do_spells,        0, NONE           },
  { "breath",        FIG, 0,           do_breath,        0, NONE           },
  { "show",          DEA, REAL_IMMORT, do_show,          0, NONE           }, 
  { "debug",         DEA, SILLYLORD,   do_debug,         0, NONE           }, /* 241 */
  { "invisible",     DEA, IMMORTAL,    do_invis,         0, NONE           },
  { "gain",          RES, 0,           do_gain,          0, NONE           },
  { "instazone",     DEA, GOD,         do_instazone,     0, NONE           },
  { "disarm",        FIG, 1,           do_disarm,        0, NONE           },
  { "bonk",          RES, 0,           do_action,        0, NONE           },
  { "wizlist",       DEA, 0,           do_wizlist,       0, NONE           },
  { ";",             DEA, IMMORTAL,    do_commune,       0, NONE           },
  { "commands",      DEA, 0,           do_listcommands,  0, NONE           },
  { "clean",         DEA, IMPLEMENTOR, do_clean,         0, NONE           },
  { "noaffect",      DEA, GREATER_GOD, do_noaffect,      0, NONE           }, /* 251 */
  { "chat",          DEA, SILLYLORD,   do_chat,          0, NONE           },
  { "/",             DEA, SILLYLORD,   do_chat,          0, NONE           },
  { "logging",       DEA, SILLYLORD,   do_log,           0, NONE           },
  { "runninglog",    DEA, REAL_IMMORT, do_running_log,   0, NONE           },
  { "spy",           DEA, IMPLEMENTOR, do_char_log,      0, NONE           },
  { "file",          DEA, SILLYLORD,   do_file,          0, NONE           },
  { "police",        DEA, GREATER_GOD, do_police,        0, NONE           },
  { "notell",        DEA, 0,           do_notell,        0, NONE           },
  { "zone",          DEA, IMPLEMENTOR, do_zone,          0, NONE           },
  { "ocreate",       DEA, SILLYLORD,   do_ocreate,       0, NONE           }, /* 261 */
  { "oedit",         DEA, SILLYLORD,   do_oset,          0, NONE           },
  { "osave",         DEA, SILLYLORD,   do_osave,         0, NONE           },
  { "olook",         DEA, SILLYLORD,   do_olook,         0, NONE           },
  { "consent",       RES, 0,           do_consent,       0, NONE           },
  { "mcreate",       DEA, IMPLEMENTOR, do_mcreate,       0, NONE           },
  { "medit",         DEA, IMPLEMENTOR, do_medit,         0, NONE           },
  { "msave",         DEA, IMPLEMENTOR, do_msave,         0, NONE           },
  { "mat",           DEA, REAL_IMMORT, do_mat,           0, NONE           },
  { "gsay",          RES, 0,           do_gsay,          0, NONE           },
  { "aggr",          RES, 0,           do_aggr,          0, NONE           }, /* 271 */
  { "beep",          DEA, 2,           do_beep,          0, NONE           },
  { "channel",       RES, 0,           do_channel,       0, NONE           },
  { "auction",       RES, 7,           do_auction,       0, NONE           },
  { "gossip",        RES, 7,           do_gossip,        0, NONE           },
  { "arena",         STA, 0,           do_arena,         0, NONE           },
  { "cls",           DEA, 0,           do_cls,           0, NONE           },
  { "prompt",        DEA, 0,           do_prompt,        0, NONE           },
  { "listhelp",      DEA, 0,           do_listhelp,      0, NONE           },
  { "oload",         DEA, CREATOR,     do_oload,         0, NONE           },
  { "delete",        DEA, IMPLEMENTOR, delete_entry,     0, NONE           }, /* 281 */
  { "reset",         RES, 0,           do_reset,         0, NONE           },
  { "appraise",      RES, 0,           do_examine,       0, NONE           },
  { "report",        RES, 0,           do_report,        0, NONE           },
  { "passwd",        DEA, IMPLEMENTOR, do_passwd,        0, NONE           },
  { "turn",          SLE, 0,           do_turn,          0, NONE           },
  { "scan",          STA, 0,           do_scan,          0, NONE           },
  { "hitall",        STA, 0,           do_hitall,        0, NONE           },
  { "split",         RES, 0,           do_split,         0, NONE           },
  { "listskills",    DEA, SILLYLORD,   do_list_skills,   0, NONE           },
  { "fill",          RES, 0,           do_fill,          0, NONE           }, /* 291 */
  { "set",           DEA, DEMIGOD,     do_set,           0, NONE           },
  { "stats",         DEA, SILLYLORD,   do_statistics,    0, NONE           },
  { "noexits",       DEA, 0,           do_noexits,       0, NONE           },
  { "oldnews",       DEA, 0,           do_oldnews,       0, NONE           },
  { "slice",         STA, 0,           do_slice,         0, NONE           },
  { "mail",          RES, 0,           do_mail,          0, NONE           },
  { "kills",         DEA, 0,           do_kills,         0, NONE           },
  { "berserk",       STA, IMPLEMENTOR, do_berserk,       0, NONE           },
  { "chaos",         DEA, GREATER_GOD, do_chaos_open,    0, NONE           },
  { "ticks",         DEA, SILLYLORD,   do_ticks,         0, NONE           }, /* 301 */
  { "timer",         DEA, SILLYLORD,   do_timer,         0, NONE           },
  { "linkdead",      DEA, SILLYLORD,   do_linkdead,      0, NONE           },
  { "map",           RES, 0,           do_map,           0, NONE           },
  { "fine",          DEA, GREATER_GOD, do_fine,          0, NONE           },
  { "data",          DEA, LESSER_GOD,  do_data,          0, NONE           },
  { "linkload",      DEA, SILLYLORD,   do_linkload,      0, NONE           },
  { "choose",        RES, 1,           do_choose,        0, NONE           },
  { "crash",         DEA, IMPLEMENTOR, do_crash,         0, NONE           },
  { "skills",        DEA, 0,           do_skills,        0, NONE           },
  { "trashcan",      DEA, GREATER_GOD, do_trashcan,      0, NONE           }, /* 311 */
  { "maxplayers",    DEA, SILLYLORD,   do_maxplayers,    0, NONE           },
  { "reboot",        DEA, SILLYLORD,   do_reboot,        0, NONE           },
  { "norent",        DEA, SILLYLORD,   do_norent,        0, NONE           },
  { "bet",           DEA, 1,           do_gamble,        0, NONE           },
  { "batter",        FIG, 1,           do_batter,        0, NONE           },
  { "doorbash",      STA, 1,           do_doorbash,      0, NONE           },
  { "pwhere",        DEA, REAL_IMMORT, do_where,         0, NONE           }, /* 318 */
  { "mwhere",        DEA, CREATOR,     do_where,         0, NONE           }, /* 319 */
  { "mstat",         DEA, CREATOR,     do_stat,          0, NONE           }, /* 320 */
  { "pstat",         DEA, DEMIGOD,     do_stat,          0, NONE           }, /* 321 */
  { "rstat",         DEA, REAL_IMMORT, do_stat,          0, NONE           }, /* 322 */
  { "setall",        DEA, IMPLEMENTOR, do_setall,        0, NONE           }, /* 323 */
  { "offset",        DEA, IMMORTAL,    do_offset,        0, NONE           },
  { "listspells",    DEA, SILLYLORD,   do_list_spells,   0, NONE           },
  { "foreach",       DEA, IMPLEMENTOR, do_foreach,       0, NONE           },
  { "donate",        STA, 1,           do_donate,        0, NONE           },
  { "nonew",         DEA, GOD,         do_nonew,         0, NONE           },
  { "view",          DEA, REAL_IMMORT, do_viewlog,       0, NONE           },
  { "events",        DEA, SILLYLORD,   do_events,        0, NONE           },
  { "cancel",        DEA, SILLYLORD,   do_cancel,        0, NONE           },
  { "oldload",       DEA, REAL_IMMORT, do_oldload,       0, NONE           },
  { "saveworld",     DEA, IMPLEMENTOR, save_world,       0, NONE           },
  { "retreat",       FIG, 0,           do_retreat,       0, NONE           },
  { "motd",          DEA, 0,           do_motd,          0, NONE           },
  { "proficiencies", DEA, 0,           do_proficiencies, 0, NONE           },
  { "sacrifice",     RES, 0,           do_sacrifice,     0, NONE           },
  { "disable",       DEA, SILLYLORD,   do_disable,       0, CMDF_NODISABLE },
  { "enable",        DEA, SILLYLORD,   do_enable,        0, CMDF_NODISABLE },
  { "priority",      DEA, 0,           do_priority,      0, NONE           },
  { "away",          DEA, IMMORTAL,    do_away,          0, NONE           },
  { "aid",           STA, 0,           do_aid,           0, NONE           },
  { "bandage",       STA, 0,           do_aid,           0, NONE           },
  { "finger",        DEA, 0,           do_finger,        0, NONE           },
  { "terminal",      DEA, 0,           do_terminal,      0, NONE	   },
  { "donations",     DEA, 0,           do_donations,     0, NONE           },
  { "remote",        DEA, SILLYLORD,   do_open_remote,   0, NONE           },
  { "\n",            DEA, ABS_MAX_LVL, NONE,             0, NONE           }
};

#endif
